import {  ReactNode } from "react";
// import { usePathname } from "next/navigation";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SiteHeader } from '@/components/site-header';
import { ThemeProvider } from "@/components/theme-provider";
import PromptDialog from "@/app/components/promptDialog";
import ClientProvider from "./SessionProvider";
import ClientRootProvider from '@/app/ClientRootProvider';
import ClientRouteHandler from "./ClientRouteHandler";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientRootProvider>
          <ClientProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <SiteHeader />
              <ClientRouteHandler>
                {children}
                <PromptDialog />
              </ClientRouteHandler>
          </ThemeProvider>
          </ClientProvider>
        </ClientRootProvider>
      </body>
    </html>
  );
}
